[package]
name = "sequencer-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
revm = { workspace = true }
revm-primitives = { workspace = true }
reth = { workspace = true }
axum.workspace = true
tokio.workspace = true
serde.workspace = true
actix-web = "4"
serde_json = "1.0"
